### ISSUE TITLE
Earlier detection of missing type hints

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#115]
Currently, this succeeds without error:
```python
def f(x) -> int:
    return x

pl = sl.Pipeline([f])
tg = pl.get(int)
```
But calling `tg.compute(int)` raises `TypeError: f() missing 1 required positional argument: 'x'`. It would be easier to understand what went wrong if the pipeline would raise when the provider is inserted.

Is see no valid use case for a provider like this. In the given form, it will always lead to an exception during `compute`. If there is a default value, it works. But the default can never be overridden by the pipeline. So IMHO, it shouldn't be there at all in a provider.
Note that this is actually used here: https://github.com/scipp/sciline/blob/262fac770ac49de60045a40a019b458271fb269e/src/sciline/pipeline.py#L425 But since `label` can never be provided by the pipeline, the argument can simply be removed from the lambda: `lambda: label` (This does not work completely here because the lambda is defined in a loop and would incorrectly bind the first definition of `label` instead of the one of the current loop iteration.)

**Comment by SimonHeybrock** [comment]
Does #116 fix this?

**Comment by jl-wynen** [comment]
It pushes the detection forward to `pipeline.get`. But not to the constructor.
