### ISSUE TITLE
Unexpected name of providers in Pipeline HTML repr for python 3.9

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#119]
Currently it is using `__qualname__` to retrieve the name of the provider.
But up to python 3.9, `NewType` objects are functions and doesn't update ``__qualname__`` of the function according to its name.
Hence the `__qualname__` returns `NewType.<locals>.new_type`.

![image](https://github.com/scipp/sciline/assets/17974113/42178ffd-7644-4925-ab68-04d5f91557aa)

TODO:
- [ ] Update provider name parsing to include `NewType` of python 3.9. to be consistent with later versions.
- [ ] Add tests that checks if the expected names are included in the html result.

**Comment by SimonHeybrock** [comment]
We will drop 3.9 soon, no need to fix.
