### ISSUE TITLE
Unhashable type agruments as a return type.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#122]
I bumped into this error when I tried to add a callable object as a parameter.
It's because `Callable` accepts either `...` or a `list` of types as first type argument.
I needed it because I wanted to pass a function to a provider, and `Callable` can't be inherited to another class,
so I had to use ``Callable`` directly.

Should we have a helper function that turn list into tuple in a tested type arguments...?

```python
from typing import Callable
import sciline as sl

pl = sl.Pipeline({
params={Callable[[int], int]: lambda x: x}
})  # Raises TypeError: unhashable type: 'list'
```

**Comment by SimonHeybrock** [comment]
Can you create an alias? This seems to work for me:

```python
from typing import NewType, Callable
import sciline

MyFunc = NewType('MyFunc', Callable[[int], int])

def myfunc(x: int) -> int:
    return x * 2

def make_func() -> MyFunc:
    return myfunc

pipeline = sciline.Pipeline([make_func])
func = pipeline.compute(MyFunc)
func(2)
```

**Comment by YooSunYoung** [comment]
It works, but then pylance and mypy complains that ``Callable[[int], int]`` is not a class.
And ``pylance`` doesn't recognize the new type as a type...

But I agree. I should've made them into a new type.

**Comment by SimonHeybrock** [comment]
Since we are now using the type hints as node names in NetworkX this cannot be fixed, unless we want to define our own way of "hashing", e.g., by converting to a string. I currently don't see a good justification for such a complication (which would probably risk introducing some subtle bugs), so I'll close as wontfix.
