### ISSUE TITLE
Type name parsing 

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#129]
``typing.Callable`` type itself and type aliases of ``Callable`` with type arguments, i.e. ``Callable[[...]. int]``
doesn't have ``__name__`` in ``python3.9``
and ``__name__`` doesn't show the type arguments ``>=python3.10``.

It caused the docs build error using sphinx extension.

**Comment by YooSunYoung** [comment]
I just tried filtering ``Callable`` and then found out...

```python
from typing import Callable, get_origin
from collections.abc import Callable as CallableABC

get_origin(Callable[[int], int]) is CallableABC  # True
get_origin(Callable[[int], int]) is Callable  # False
```

**Comment by YooSunYoung** [comment]
And it'll be hard to maintain if we deal with all these exceptions.

Should we have a high-level wrapper that always just falls back to something general
maybe ``str(ty)`` if anything goes bad...?

**Comment by jl-wynen** [comment]
What exactly fails? Is it a problem with sphinx or does it happen inside of sciline?

**Comment by YooSunYoung** [comment]
> What exactly fails? Is it a problem with sphinx or does it happen inside of sciline?

In `sciline.sphinxext.domain_types`.
