### ISSUE TITLE
A new approach for "parameter tables"

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/sciline#141]
### Context

[Parameter Tables](https://scipp.github.io/sciline/user-guide/parameter-tables.html) provide a mechanism for repeating parts of or all of a computation with different values for one or more parameters. This allows for a variety of use cases, similar to map, reduce, and groupby operations in other systems.

Parameter tables are a significant complication in the implementation of `Pipeline`. It also makes it conceptually hard to define what a `Pipeline` "is". We have recently seen a number of places where parameter tables get in the way when thinking about or implementing changes or new features.

### Idea

- Remove parameter-table support from `Pipeline` (*in practice this can be done *after* the suggested approach is implemented, both can coexists for a while to ease transition*).
- Implement param-table features as **map-reduce** and **map-groupby** operations on `TaskGraph`
- This will give an array-like structure (possibly multi-dimensional) with coordinates to parts (or all) of a task graph.
- Conceptually nothing new is introduced (even though the new approach offers more flexibility in some cases), but it factors the complications out of `Pipeline`, into `TaskGraph` or helper functions.

#### Start

For simplicity, I will be drawing graphs using only the data nodes, without compute nodes.
Consider a simple graph named `graph`:

```mermaid
graph TD;
  A-->B-->C;
```

We assume this was creating using `Pipeline.get(C)`.

#### Map

```python
graph.map((A, [1,2,3])
```
would result in
```mermaid
graph TD;
  A1-->B1-->C1;
  A2-->B2-->C2;
  A3-->B3-->C3;
```
#### Map-reduce

```python
graph.map((A, [1,2,3]), at=B).sum()  # sum all dims (here A) at B
```
would result in
```mermaid
graph TD;
  A1-->B1-->B-->C;
  A2-->B2-->B;
  A3-->B3-->B;
```

### Map-groupby-reduce

Modulo some syntax subtleties that I need to think about (overall it may make more sense to move the "at" arguments to the reduction step, I think):

```python
graph.map((A, [1,2,3]), at=B) \  # adds dimension coord
     .label(L, (A, ['a', 'b', 'a'])) \   # adds non-dim coord
     .groupby(L) \
     .sum()
```
results in

```mermaid
graph TD;
  A1-->B1-->Ba-->Ca;
  A2-->B2-->Bb-->Cb;
  A3-->B3-->Ba;
```

#### More examples

I will provide more, if the overall idea sees positive feedback. Brief summary:

- Multiple map operations, resulting in multi-dim node structure
- Small syntax complications if we need to `map-reduce` at multiple points, i.e., when cutting a diamond graph
- `map.reduce` with custom functions (instead of built-ins like `sum`)
- Using coordinate/labels to slice graphs that were created using `map`.

**Comment by YooSunYoung** [comment]
How do you use custom function for ``map.reduce``?


In this example,
```python
graph.map((A, [1,2,3]), at=B).sum()  # sum all dims (here A) at B
```
```mermaid
graph TD;
  A1-->B1-->B-->C;
  A2-->B2-->B;
  A3-->B3-->B;
```
Going from `A1` to `B1` should already be in the graph
but a function for going from `B1` to `B` will not be in the graph.

**Comment by jl-wynen** [comment]
This is definitely something we should discuss offline!

I need to go through more examples to develop an understanding. But here are my first impressions:

- Composing operations is good!
- If we can make the relationship with dimensions more explicit / apparent, we can maybe reuse some intuition that users built up when using Scipp. (This is a niche type of intuition that most scientists don't share.)
- I agree that the `at` argument should be part of the reduction / grouping. I don't understand what it even does in `map`.
- How do the `A*` nodes get their values? Does it create n new types that need to be filled with parameters? Or do you still envision something like a table to fill the replicated parameters?
- 'map' is normally used for applying the same function to multiple pieces of data. Here, it is applied to data. This may just be a naming issue. Or is there a deeper reason for the name?
- The labelling approach might not work well with 'multi-dim' graphs. It requires passing labels for each 'coord' value of A. But A may be parametrised in multiple dims.

**Comment by nvaytet** [comment]
> I agree that the at argument should be part of the reduction / grouping. I don't understand what it even does in map.

Yes, I would have expected something like `graph.map((A, [1,2,3])).sum(at=B)` ?

**Comment by jokasimr** [comment]
I think this is an interesting approach and seems like it could be very useful to describe complex data processing workflows succinctly.
However, there are still some questions
* memory usage / how to make things efficient without us having to do too much work,
* what the api should look like,
* what the capabilities / features this system actually has,
 
One option that I think could partially answer those questions, is to stay close to and perhaps also implement this in terms of the `dask.Bag` api.
We're probably only going to need a subset of it.

**Comment by jokasimr** [comment]
I also think we should be prepared that not all workflows will be possible to represent as DAGs. For example, Aaron said in his presentation yesterday that they sometimes had to go back and retry earlier parts of the workflow based on a result later in the workflow, that kind of workflow is not easily represented by a DAG. Don't know if that part was very NMX specific.

**Comment by jl-wynen** [comment]
> I also think we should be prepared that not all workflows will be possible to represent as DAGs. For example, Aaron said in his presentation yesterday that they sometimes had to go back and retry earlier parts of the workflow based on a result later in the workflow, that kind of workflow is not easily represented by a DAG. Don't know if that part was very NMX specific.

We were aware of this from the beginning but decided against supporting it in order to not overcomplicate our graphs. Basically, we decided to not support explicit branching and looping on the graph level.

See the SANS direct beam iteration for another case where a workflow needs to be looped. If we ever were to build a full SXD workflow, we'd have to do something similar.

**Comment by jokasimr** [comment]
Yeah I don't suggest we should make the graphs support branching or looping. I think that kind of logic fits best in a simple python script.

**Comment by SimonHeybrock** [comment]
> I think this is an interesting approach and seems like it could be very useful to describe complex data processing workflows succinctly. However, there are still some questions
> 
>     * memory usage / how to make things efficient without us having to do too much work,

Certainly worth thinking about, but note that there is no difference in this respect to the currently solution via [Parameter Tables](https://scipp.github.io/sciline/user-guide/parameter-tables.html) part of `Pipeline`. The new system might provide an extra advantage here, since it would be easy to support, e.g., hierarchical reduction operations that reduce memory consumption by reducing pairwise.

> One option that I think could partially answer those questions, is to stay close to and perhaps also implement this in terms of (a thin wrapper around) the `dask.Bag` api. We're probably only going to need a subset of it.

The API I have in mind certainly has some similarities with `dask.Bag`. But note that `bag` is not ordered, whereas at least our current implementation *does* define an order. Also, we cannot use Dask for this, as `bag` is a Dask collection that creates a task graph, whereas we already have one, that we want to transform.

My current idea is to implement a stand-alone library (not in Sciline) that implements the graph transformations in a generic manner, with no link to Sciline. It should, e.g., be able to map over (ideally) all the widespread types such as Numpy arrays, Pandas Series/DataFrame, Xarray and Scipp variables, and maybe even the new [ragged](https://github.com/scikit-hep/ragged/).
