### ISSUE TITLE
More flexible parameter type handling

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#144]
Currently, Pipeline is very strict about the types of parameters. The concrete value must exactly match the parameter key (type). It is good to have some validation but we should be more flexible.

I think we should convert the given values to the parameter key. This would allow, e.g.,
```python
params = {
    numbers.Real: 3.14,
    Path: "some/path",
    sc.DataGroup: {'a': 'dict'},
}
```
As mentioned in point 3 from https://github.com/scipp/sciline/issues/139, we have #75 but that is not sufficient for the above.

**Comment by SimonHeybrock** [comment]
I think I generally agree, but would like to add a negative example, so we can base our decision also on that:

```python
A = NewType('A', float)
B = NewType('B', float)
my_param = A(1.5)
params = {
    A: 3.14,
    B: "my_param,  # converts an A to an B?
}
```

Can this be prevented, while still supporting what is suggested above?

**Comment by jl-wynen** [comment]
> Can this be prevented, while still supporting what is suggested above?

I think it could be by comparing the type to *all* parameters and rejecting it if there is any match. So it's not exactly cheap.

Alternatively, we could check whether the value is an instance of `NewType` or `TypeAliasType` and not perform conversions in that case. But that would somewhat limit the use of type aliases that weren't meant as Sciline domain types. But that seems like a rare edge case.

**Comment by SimonHeybrock** [comment]
I think we can consider this fixed by the removal if the `isinstance` checks?
