### ISSUE TITLE
Should `Pipeline.visualize` default to show the full graph if no keys are given?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/sciline#177]
See title. I think this would be quite useful.

**Comment by jl-wynen** [comment]
Comment from #181:
> We have a number of pipelines across multiple projects now. And we compose new pipelines from them. It is currently very difficult to inspect a pipeline in its entirety to, e.g., find out what it can produce, or how it does a certain operation. It would be a great help if we could just visualize a pipeline without having to already know what it can produce or what products depend on the subgraph you are currently interested in.

**Comment by jokasimr** [comment]
Fixed in https://github.com/scipp/sciline/pull/188
