### ISSUE TITLE
Param setting not working with default values

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#182]
For essimaging I wanted to make some arguments optional,

```python

import sciline as sl
from typing import NewType

OptionalInt = NewType("OptionalInt", int | None)


def foo(a: OptionalInt) -> str:
    return str(a) if a is not None else "Here is your default message."


wf = sl.Pipeline([foo], params={OptionalInt: OptionalInt(None)})
wf.compute(str)

# 'Here is your default message.'

```

But if the argument has a default value of None, it fails.

```python

import sciline as sl
from typing import NewType

OptionalInt = NewType("OptionalInt", int | None)


def foo(a: OptionalInt = None) -> str:
    return str(a) if a is not None else "Here is your default message."


wf = sl.Pipeline([foo], params={OptionalInt: OptionalInt(None)})
wf.compute(str)

# sciline.handler.UnsatisfiedRequirement: ('No provider found for type', typing.Optional[__main__.OptionalInt])

```

Is it a known limitation or a bug...?

**Comment by SimonHeybrock** [comment]
The error message shows that something odd is going on: Why is it looking for `typing.Optional[__main__.OptionalInt]` and not `__main__.OptionalInt`?

**Comment by jokasimr** [comment]
This is because of how [`get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) worked prior to python 3.11.

> Changed in version 3.11: Previously, Optional[t] was added for function and method annotations if a default value equal to None was set. Now the annotation is returned unchanged.

I've verified that this bug is not present in 3.11.

**Comment by jokasimr** [comment]
What's best to do? Should we

* bump the minimum python version of sciline to 3.11 or
* try to add a special case to fix the bug for versions below 3.11 or
* do nothing ;)

**Comment by MridulS** [comment]
> do nothing ;)

Just wait it out? https://scientific-python.org/specs/spec-0000/#support-window Python 3.10 could be dropped in a bit :)

**Comment by jokasimr** [comment]
> Just wait it out? https://scientific-python.org/specs/spec-0000/#support-window Python 3.10 could be dropped in a bit :)

3.10 already out? Looking at that schedule makes me feel old. But yeah this could well be the best option

**Comment by jokasimr** [comment]
The proposed fix was insufficient so it was decided to do nothing instead.
