### ISSUE TITLE
Support any iterable in `Pipeline.get`

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#47]
Right now, when using, e.g., a list (`pipeline.get([A, B])`) it raises `TypeError: unhashable type: 'list'`.
For better usability, it should allow any `Iterable[type]` and construct a tuple if need be internally.

**Comment by SimonHeybrock** [comment]
If I remember correctly I copied this from a Dask limitation, or rather the confusing the behavior that it always returned a tuple, even if the input was a list.

**Comment by jl-wynen** [comment]
I don't see this as a problem. We would be relaxed about what we accept as input and strict about what we return. This is a good pattern, IMHO.

**Comment by SimonHeybrock** [comment]
👍
