### ISSUE TITLE
Documentation with links to type aliases?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/sciline#61]
The following is not really a problem of Sciline itself, it does however severely impact usability of documentation of downstream projects.

Sphinx, in particular with https://github.com/tox-dev/sphinx-autodoc-typehints, "expands" type hints to aliases defined with `typing.NewType`. That is, instead of a link to the docs of the alias, we just get a long to `NewType` (which is useless) and the name of the alias.

According to https://github.com/tox-dev/sphinx-autodoc-typehints/issues/216#issuecomment-1026588210 this might be intentional. Can this be changed in the extension as suggested in the comment? Do we need our own extension?

**Comment by YooSunYoung** [comment]
I would like to work on it since it affects the documentation of ``ess*`` packages.

**Comment by SimonHeybrock** [comment]
Not sure this should be closed: While we have a solution in our `copier_template` now, this is not readily available or usable by other Sciline users. Maybe we can add this approach to the Sciline docs, or maybe you have a better idea?

**Comment by jl-wynen** [comment]
I was only thinking about internal users. So having it in the template would automatically apply this to all packages at some point.

If we want to provide it to other users, too, we should implement a sphinx plugin. Though I'm not sure how that would interact with autodoc.

**Comment by SimonHeybrock** [comment]
Not saying we have to necessarily provide such a solution, but maybe we should either keep this issue open, or add a docs section?
