### ISSUE TITLE
Add `_repr_html_` for `TaskGraph`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/sciline#70]

**Comment by SimonHeybrock** [comment]
> List of the providers in alphabetical order.

We should order alphabetically by the type that is provided, the provider names may be of secondary interest.

There is also a third case, parameter tables. So a good starting point may be:

- Table with 3 columns
- First column: Type
- Second column: category (provider/param/param table)
- Third column: provider name/param value/summary of param table, depending on what we have in second column

Instead of a table with the category in the second column, one could also choose to output in three sections, each with 2 columns (1 and 3 above).

I think the main work will be to implement gathering all the info, we can then try different options for representing it?

**Comment by SimonHeybrock** [comment]
> or each provider, indicate if its preconditions are satisfied, perhaps display what is missing?

Yes, we could list all the dependencies, may indicate with color if it is satisfied?

**Comment by jokasimr** [comment]
> I think the main work will be to implement gathering all the info

Currently `Pipeline` stores parameters as provider functions without arguments.
Therefore we can not directly determine if the pipeline was initiated with a provider function without arguments or with a parameter.

We could use some heuristics.
Would it be correct to display every zero-arguments provider as a parameter?
I guess it would make sense if the provider functions are pure, but I don't know if that is a guarantee or just a recommendation from sciline to make the providers pure.

Another stricter option would be to treat every zero-arguments anonymous function as a parameter.

A third option would be to explicitly store information about what types were provided as parameters and what types were provided as functions.

**Comment by SimonHeybrock** [comment]
> We could use some heuristics.

We can use the same approach as in the graph visualization code, no tricks or heuristics required: https://github.com/scipp/sciline/blob/f04f65e5f9fec94987de5713b823912af51dfad8/src/sciline/visualize.py#L110-L114

**Comment by SimonHeybrock** [comment]
Reopening since only `Pipeline._repr_html_` has been implemented so far.
