### ISSUE TITLE
Support keyword arguments in providers

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#76]
All arguments are passed positionally. So we cannot use keyword-only arguments in providers.

But since providers are typically not just a thin wrapper but encode some logic themselves, we may want to use them like regular functions. So following our style of requiring keyword arguments in many places, we should allow the same here.

**Comment by SimonHeybrock** [comment]
I used this initially, but dropped it, since it made it harder to use Dask, which does not really place nice with kwargs. I think there was a way to get it to work somehow, but it did not feel straightforward.
