### ISSUE TITLE
Docstring of domain types for providers.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#85]
In the built documentation pages,
individual API reference page for domain types don't really have much information.

Should we have a separate page for them or add doc string manually to the new type?

And the ``Scope`` inherited type pages are also a bit confusing... it'll be nice to have what it inherited.

**Comment by SimonHeybrock** [comment]
> Should we have a separate page for them or add doc string manually to the new type?

Can you clarify what you are asking? There are no domain types in Sciline?

**Comment by YooSunYoung** [comment]
I meant the api references of ``ess.*`` packages.
The auto-generated document doesn't seem to be useful except that it shows all available types and providers in one place.

**Comment by SimonHeybrock** [comment]
Then this looks like a duplicate of #61?

**Comment by YooSunYoung** [comment]
> Then this looks like a duplicate of #61?

Right...! Sorry! I'll close this one.
